const styles = {
  weaponIconFallback: (size) => ({
    width: size,
    height: size,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 2,
    backgroundColor: 'action.hover',
    color: 'text.secondary',
    fontWeight: 700,
    fontSize: size > 50 ? '1.25rem' : '0.9rem',
  }),
  weaponIcon: (size) => ({
    width: size,
    height: size,
    objectFit: 'contain',
    borderRadius: 2,
    backgroundColor: 'action.hover',
  }),
  detailsPanel: { p: { xs: 2, sm: 2.5 }, boxSizing: 'border-box' },
  detailsDeselectButton: { mb: 2 },
  detailsHeader: { display: 'flex', gap: 2, alignItems: 'center', mb: 2 },
  detailsHeaderContent: { minWidth: 0 },
  detailsName: { overflowWrap: 'anywhere' },
  detailsTags: { display: 'flex', gap: 0.75, flexWrap: 'wrap', mt: 0.5 },
  detailsDescription: { whiteSpace: 'pre-line', mb: 2 },
  detailsStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: { xs: 0.75, sm: 1.25 },
    alignItems: 'start',
  },
  detailsNoStats: { gridColumn: '1 / -1' },
  detailsGroupLabel: { fontWeight: 700, display: 'block', mb: 0.5, textAlign: 'center' },
  detailsStatList: { display: 'flex', gap: 0.5, flexWrap: 'wrap', justifyContent: 'center' },
  weaponCard: (isSelected) => ({
    minWidth: 0,
    height: '100%',
    borderColor: isSelected ? 'primary.main' : 'divider',
    backgroundColor: isSelected ? 'action.selected' : 'background.paper',
  }),
  weaponCardAction: { height: '100%', p: 1 },
  weaponCardContent: { display: 'grid', justifyItems: 'center', gap: 0.75 },
  weaponCardName: { width: '100%', overflowWrap: 'anywhere', lineHeight: 1.2 },
  browser: { height: '100%', minHeight: 0, display: 'flex', flexDirection: 'column' },
  browserControls: { display: 'flex', flexDirection: 'column', flex: '0 0 auto' },
  browserTitle: { mb: 1 },
  filterGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' },
    gap: 1.5,
    mb: 1.5,
  },
  selectedWeaponContainer: { flex: '1 1 auto', minHeight: 0, overflowY: 'auto', mt: 2 },
  weaponList: { flex: '1 1 auto', minHeight: 0, overflowY: 'auto', pr: { sm: 0.5 } },
  availableWeaponsBar: { display: 'flex', justifyContent: 'space-between', gap: 1, mt: 1, mb: 1 },
  emptyState: { p: 3, textAlign: 'center' },
  virtualList: (rowCount, rowHeight) => ({ position: 'relative', height: rowCount * rowHeight }),
  virtualGrid: (columnCount, firstVisibleRow, rowHeight, rowGap) => ({
    position: 'absolute',
    top: firstVisibleRow * rowHeight,
    left: 0,
    right: 0,
    display: 'grid',
    gridTemplateColumns: `repeat(${columnCount}, minmax(0, 1fr))`,
    gridAutoRows: rowHeight - rowGap,
    gap: `${rowGap}px`,
  }),
  statsSection: { mb: 0.5 },
  statsLabel: { fontWeight: 600, display: 'block', mb: 0.25 },
  statsList: { display: 'flex', gap: 0.5, flexWrap: 'wrap' },
  accordion: { '&:before': { display: 'none' } },
  poolSummary: { width: '100%', pr: 1 },
  poolSummaryStats: { mt: 0.5 },
  farmableTogetherTitle: { mb: 1 },
  farmableWeaponItem: { py: 0.25 },
  farmableWeaponStats: { display: 'flex', gap: 0.5, flexWrap: 'wrap', mt: 0.25 },
  matchingWeaponChip: {
    backgroundColor: 'warning.light',
    color: 'warning.contrastText',
    borderColor: 'warning.main',
  },
  resultsPanel: { p: { xs: 2, sm: 3 }, height: '100%', minHeight: 0, boxSizing: 'border-box' },
  resultsPanelWithList: {
    p: { xs: 2, sm: 3 },
    height: '100%',
    minHeight: 0,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
  },
  resultsTitle: { mb: 0.75 },
  resultsTitleWithList: { flex: '0 0 auto', mb: 0.75 },
  resultsList: { flex: '1 1 auto', minHeight: 0, overflowY: 'auto' },
}

export default styles
