const styles = {
  page: {
    '--factory-accent': '#176a63',
    '--factory-border': '#dce3e4',
    color: '#243436',
    '& h2, & h3, & p': {
      margin: '0',
    },
    '& h2': {
      fontSize: 'clamp(24px, 3vw, 32px)',
      letterSpacing: '-1px',
      margin: '4px 0',
    },
    '& h3': {
      fontSize: '16px',
      fontWeight: '650',
    },
    '& p': {
      color: '#647477',
      fontSize: '12px',
      lineHeight: '1.6',
    },
    '& .factory-heading': {
      display: 'flex',
      alignItems: 'flex-start',
      flexDirection: 'column',
      gap: '12px',
      padding: '4px 0 8px',
    },
    '& .factory-eyebrow': {
      color: 'var(--factory-accent)',
      fontSize: '10px',
      letterSpacing: '2px',
      fontWeight: '700',
    },
    '& .factory-workspace': {
      display: 'grid',
      gridTemplateColumns: 'clamp(210px, 18vw, 280px) minmax(0, 1fr) clamp(220px, 20vw, 300px)',
      gap: '12px',
      alignItems: 'stretch',
      height: '100%',
      minHeight: 0,
    },
    '& .factory-panel': {
      border: '1px solid var(--factory-border)',
      borderRadius: '12px',
      background: '#fff',
      overflow: 'hidden',
    },
    '& .factory-land-heading': {
      display: 'flex',
      gap: '10px',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '16px 18px 8px',
      flexWrap: 'wrap',
    },
    '& h3 span': {
      color: '#758588',
      fontSize: '12px',
      fontWeight: '400',
      marginLeft: '8px',
      whiteSpace: 'nowrap',
    },
    '& .factory-instructions': {
      padding: '0 18px 12px',
    },
    '& .factory-grid-toolbar': {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: '8px',
      padding: '0 12px 12px',
    },
    '& .factory-zoom-controls': {
      display: 'flex',
      alignItems: 'center',
      marginLeft: 'auto',
      fontSize: '12px',
      gap: '4px',
      '& button': { minWidth: '32px' },
      '& span': { minWidth: '40px', textAlign: 'center' },
    },
    '& .factory-port-legend': {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      color: '#657573',
      fontSize: '10px',
      lineHeight: 1,
      flexWrap: 'wrap',
    },
    '& .factory-port-key': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '16px',
      height: '16px',
      borderRadius: '50%',
      color: '#fff',
      fontSize: '9px',
      fontWeight: 700,
      marginLeft: '3px',
      '&.input.belt, &.output.belt': { background: '#176a63' },
      '&.input.pipe, &.output.pipe': { background: '#7646a8' },
    },
    '& .factory-grid-scroll': {
      overflow: 'auto',
      padding: '12px',
      background: '#edf2f1',
      flex: 1,
      minHeight: 0,
      overscrollBehavior: 'contain',
    },
    '& .factory-grid-stage': {
      height: '100%',
      display: 'grid',
      placeItems: 'center',
    },
    '& .factory-grid': {
      display: 'grid',
      gridTemplateColumns: 'repeat(20, minmax(0, 1fr))',
      gridTemplateRows: 'repeat(20, minmax(0, 1fr))',
      flexShrink: 0,
      minWidth: 0,
      margin: 0,
      aspectRatio: '1',
      borderTop: '1px solid #ccd8d4',
      borderLeft: '1px solid #ccd8d4',
      background: '#f8faf8',
      position: 'relative',
    },
    '& .factory-cell': {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: '0',
      minHeight: '0',
      padding: '1px',
      border: '0',
      borderRadius: '0',
      borderRight: '1px solid #d5ded9',
      borderBottom: '1px solid #d5ded9',
      background: 'transparent',
      position: 'relative',
    },
    '& .factory-cell:nth-child(5n)': {
      borderRightColor: '#aebfb7',
    },
    '& .factory-cell:nth-child(n+81):nth-child(-n+100), & .factory-cell:nth-child(n+181):nth-child(-n+200), & .factory-cell:nth-child(n+281):nth-child(-n+300), & .factory-cell:nth-child(n+381):nth-child(-n+400)': {
      borderBottomColor: '#aebfb7',
    },
    '& .factory-cell:hover, & .factory-cell.preview': {
      background: '#c8e4d9',
      boxShadow: 'inset 0 0 0 1px var(--factory-accent)',
    },
    '& .factory-cell.occupied': {
      background: '#e0ebe5',
    },
    '& .factory-cell.selected': {
      background: '#bbdbcc',
      boxShadow: 'inset 0 0 0 2px var(--factory-accent)',
    },
    '& .factory-cell.blocked': {
      background: '#f6cecc',
      boxShadow: 'inset 0 0 0 2px #b44236',
    },
    '& .factory-cell img': {
      width: '100%',
      height: '100%',
      objectFit: 'contain',
      pointerEvents: 'none',
    },
    '& .factory-machine-overlay': {
      position: 'absolute',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '3px',
      border: '1px solid #77988a',
      borderRadius: '3px',
      background: 'rgba(224, 235, 229, 0.82)',
      pointerEvents: 'none',
      zIndex: 2,
      overflow: 'hidden',
    },
    '& .factory-machine-overlay.selected': {
      border: '2px solid var(--factory-accent)',
      background: 'rgba(187, 219, 204, 0.82)',
    },
    '& .factory-machine-overlay img, & .factory-machine-overlay > svg': {
      width: '100%',
      height: '100%',
      objectFit: 'contain',
    },
    '& .factory-port-marker': {
      position: 'absolute',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '18px',
      height: '18px',
      transform: 'translate(-50%, -50%)',
      border: '2px solid #fff',
      borderRadius: '50%',
      color: '#fff',
      fontSize: '9px',
      fontWeight: 800,
      lineHeight: 1,
      boxShadow: '0 1px 3px rgba(25, 49, 43, 0.45)',
      zIndex: 3,
      pointerEvents: 'auto',
    },
    '& .factory-port-marker.input.belt, & .factory-port-marker.output.belt': {
      background: '#176a63',
    },
    '& .factory-port-marker.input.pipe, & .factory-port-marker.output.pipe': {
      background: '#7646a8',
    },
    '& .factory-port-marker.output': {
      borderRadius: '4px',
    },
    '& .factory-cell:focus-visible, & .factory-machine-card:focus-visible': {
      outline: '2px solid var(--factory-accent)',
      outlineOffset: '-2px',
      zIndex: '1',
    },
    '& .factory-status': {
      display: 'flex',
      justifyContent: 'space-between',
      gap: '4px 12px',
      padding: '10px 16px',
      color: '#657573',
      fontSize: '11px',
      flexWrap: 'wrap',
    },
    '& .factory-sidebar': {
      display: 'grid',
      gridAutoRows: 'max-content',
      gap: '16px',
      minHeight: 0,
      minWidth: 0,
      overflowY: 'auto',
      alignContent: 'start',
      paddingRight: '4px',
    },
    '& .factory-resource-panel, & .factory-selection': {
      padding: '18px',
    },
    '& .factory-resource-panel > p': {
      margin: '8px 0 18px',
    },
    '& .factory-resource-panel > .MuiTextField-root': {
      marginBottom: '16px',
    },
    '& .factory-simulation-note': {
      padding: '12px',
      background: '#f1f5f4',
      borderRadius: '6px',
      fontSize: '12px',
    },
    '& .factory-simulation-note strong': {
      color: 'var(--factory-accent)',
    },
    '& .factory-simulation-note p': {
      marginTop: '5px',
    },
    '& .factory-selection > p': {
      marginTop: '12px',
      whiteSpace: 'pre-line',
    },
    '& .factory-selected-machine': {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      marginTop: '12px',
      fontSize: '13px',
      flexWrap: 'wrap',
    },
    '& .factory-selected-machine img': {
      width: '44px',
      height: '44px',
      objectFit: 'contain',
    },
    '& .factory-selection-actions': {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '8px',
      marginTop: '12px',
    },
    '& .factory-catalog': {
      display: 'flex',
      flexDirection: 'column',
      minWidth: 0,
      minHeight: 0,
    },
    '& .factory-catalog-heading': {
      display: 'flex',
      alignItems: 'stretch',
      justifyContent: 'space-between',
      gap: '12px',
      padding: '14px',
      flexDirection: 'column',
      flexShrink: 0,
    },
    '& .factory-catalog-heading p': {
      marginTop: '4px',
    },
    '& .factory-catalog-filters': {
      display: 'flex',
      gap: '12px',
      flexDirection: 'column',
    },
    '& .factory-catalog-filters .MuiTextField-root': {
      width: '100%',
    },
    '& .factory-machine-tray': {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      overflowY: 'auto',
      overflowX: 'hidden',
      padding: '0 12px 12px',
      minHeight: 0,
      flex: 1,
    },
    '& .factory-machine-card': {
      flex: '0 0 auto',
      padding: '8px',
      background: '#f6f8f7',
      border: '1px solid #e2e7e4',
      borderRadius: '8px',
      color: '#243436',
      display: 'grid',
      alignItems: 'center',
      flexDirection: 'column',
      gap: '10px',
      width: '100%',
      gridTemplateColumns: '40px minmax(0, 1fr) auto',
      textAlign: 'left',
    },
    '& .factory-machine-card:hover, & .factory-machine-card.selected': {
      borderColor: 'var(--factory-accent)',
      background: '#e6f0eb',
    },
    '& .factory-machine-card img, & .factory-machine-card > svg': {
      width: '40px',
      height: '40px',
      objectFit: 'contain',
      pointerEvents: 'none',
    },
    '& .factory-machine-card span': {
      fontSize: '12px',
      lineHeight: '1.4',
      overflowWrap: 'anywhere',
    },
    '& .factory-machine-card small': {
      color: '#778580',
      fontSize: '10px',
      marginTop: 0,
    },
    '& .factory-empty-results': {
      padding: '24px 0',
    },
    '& .factory-cell, & .factory-machine-card': {
      touchAction: 'none',
      userSelect: 'none',
      WebkitUserSelect: 'none',
    },
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    '& .factory-land': {
      display: 'flex',
      flexDirection: 'column',
      minWidth: 0,
      minHeight: 0,
    },
    '& .factory-cell > svg': {
      width: '100%',
      height: '100%',
    },
    '& .factory-sidebar > *': {
      minWidth: 0,
    },
    '@media (max-width: 1100px)': {
      '& h2': {
        fontSize: '24px',
      },
      '& .factory-resource-panel, & .factory-selection': {
        padding: '12px',
      },
      '& .factory-land-heading': {
        padding: '12px 12px 8px',
      },
      '& .factory-instructions': {
        padding: '0 12px 8px',
      },
    },
    '@media (max-width: 700px)': {
      '& .factory-workspace': {
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
        gridTemplateRows: 'minmax(0, 1fr) minmax(0, 1fr)',
        gap: '8px',
      },
      '& .factory-land': {
        gridColumn: '1 / -1',
        gridRow: 1,
      },
      '& .factory-sidebar': {
        gridColumn: 1,
        gridRow: 2,
      },
      '& .factory-catalog': {
        gridColumn: 2,
        gridRow: 2,
      },
      '& .factory-catalog-heading': {
        padding: '10px',
        gap: '8px',
      },
      '& .factory-catalog-heading p': {
        display: 'none',
      },
      '& .factory-machine-card': {
        gridTemplateColumns: '28px minmax(0, 1fr)',
        gap: '6px',
      },
      '& .factory-machine-card img, & .factory-machine-card > svg': {
        width: '28px',
        height: '28px',
      },
      '& .factory-machine-card small': {
        display: 'none',
      },
    },
  },
}

export default styles
